### ISSUE TITLE
日付決定

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#1]

**Comment by denari** [comment]
https://chouseisan.com/s?h=a08b517e7c48464fbed6ffc6bb62c1ed
まず立てた

**Comment by denari** [comment]
そんな気はしていたけれど、下記の結果だったのでとりあえず日付決定は見送りかな。


| 日程 | でなり | あらや  | sakasin | かぴばら | :puhitaku: | 女児 | 会場 | 
| --- | --- | --- | --- | --- | --- | --- | --- |
| 3/4(土) 13:00〜 | ○ | ○ | ○ | ○ | ○ | ○ | △ | 
| 3/5(日) 13:00〜 | ○ | ○ | △ | ○ | ○ | ○ | ○ | 
| 3/11(土) 13:00〜 | ○ | ○ | ○ | ○ | ○ | × | △ | 
| 3/12(日) 13:00〜 | ○ | ○ | ○ | ○ | ○ | × | ○ | 
| 3/18(土) 13:00〜 | × | ○ | ○ | ○ | ○ | ○ | △ | 
| 3/19(日) 13:00〜 | △ | ○ | ○ | ○ | ○ | ○ | ○ | 
| 3/25(土) 13:00〜 | ○ | ○ | ○ | × | ○ | × | △ | 
| 3/26(日) 13:00〜 | ○ | ○ | ○ | × | ○ | × | ○ | 
| 3/20(月・祝) 13:00〜 | ○ | ○ | ○ | ○ | ○ | ○ | △ | 
| コメント |  |  |  | 突発的にｘになるかもだけど，とりあえず | 今のところは何も |  | 現状 | 

1月25日に再度集計をかけて判断かな。(リマインダー設定done)

いまのところ3/19が僕の中では一番アツい。

**Comment by denari** [comment]
3/19
