### ISSUE TITLE
ロゴ・オープニング・エンディング・名刺

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#10]

**Comment by denari** [comment]
![lt07](https://cloud.githubusercontent.com/assets/5387939/22768881/5893a1d2-eec8-11e6-856e-bdb0f9545ef1.png)

**Comment by denari** [comment]
オープニングは作った。名札は間に合わないかもしれんね。笑

**Comment by denari** [comment]
ああ、エンディングできた
