### ISSUE TITLE
自己紹介LTの必要性を問う

### ISSUE THREAD

**Issue by denari** [kosen10s/lt07docs#11]
+ そもそも自己紹介LTは必要かどうか
+ 代替案はあるか

**Comment by denari** [comment]
> ボドゲとか

by なっちゃん

**Comment by denari** [comment]
LT6(in Kyoto)でやった、代替案になりそうなやつら

+ 京都観光
+ たこ焼きを焼く

**Comment by ysakasin** [comment]
Slackにもまだ入ってない初めての人がいるなら、自己紹介やった方がいいともう。
ただ、毎回自己紹介時間がかかるなーと思っている。スライド2枚までとか、制限を設けてパッパとやるのが良さそう。

**Comment by denari** [comment]
変な話だけど、本チャンLTの数が時間に対して枯渇しそうっすね。笑
普通にみんな十分数作ってきてくれるかなあ〜

**Comment by denari** [comment]
自己紹介、1分以内とするかあ。
スライドはまあ、1分ぐらい短けりゃ別に事前提出とかいらないっしょ。
20人超えたら考えるわ。笑

**Comment by denari** [comment]
1 - 3分のLT
