### ISSUE TITLE
会場手配

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#2]

**Comment by denari** [comment]
日付次第ではあるが、spicelifeが基本的には使えそう。

柏の葉も普通に言えば使えそうではある。
偉い人に聞いた感じだと、高専感を出せるのはフラーでもメリットと捉えた上で、kosen10sの会場提供ぐらいならできそうな雰囲気だった。

**Comment by denari** [comment]
done うなすけに感謝(s社)
![LGTM](http://kosen10s.net/i/LGTM_fxxk.gif)
