### ISSUE TITLE
場内での飲食物に関する調査

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#4]

**Comment by denari** [comment]
S社の場合 : 飲食OK、飲酒は控える、臭いに気をつける
F社の場合 : 多分納豆NG、畳を汚さないように一応気をつける

まあこんなとこかな。

**Comment by denari** [comment]
> S社の場合 : 飲食OK、飲酒は控える、臭いに気をつける

この通り

**Comment by unasuke** [comment]
まあ飲酒いいと思うけどね

**Comment by denari** [comment]
乱れるかあ。
