### ISSUE TITLE
connpassでのイベント作成

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#5]

**Comment by denari** [comment]
S社の場合 : 飲食OK、飲酒は控える、臭いに気をつける
F社の場合 : 多分納豆NG、畳を汚さないように一応気をつける

まあこんなとこかな。

**Comment by denari** [comment]
https://kosen10s.connpass.com/event/50772/

とりあえず置いておいた

**Comment by denari** [comment]
もうエンハンスしないっしょ!(面倒)
