### ISSUE TITLE
当日の運営手伝いマンにやってもらうことをリスト化

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt07docs#7]

**Comment by denari** [comment]
LT05のときのやつ

---

# 人を割り振るやつ
- 会場でよしな動いてもらえる人 ( unasuke しか無理 )
- 懇親会までの案内・懇親会仕切り ( denariやりました )
- 飲食物調達仕切り
# 人を割り振ってないやつ
- 飲食物調達(2人)

**Comment by denari** [comment]
これだけっしょ!!

**Comment by e10dokup** [comment]
買い出しなら任せろー（バリバリ）
